language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

sudo: false
before_script:
  - export PATH=~/.composer/vendor/bin/:$PATH
  - composer install --dev --no-interaction ;
  - git clone git://github.com/zenovich/runkit.git && cd runkit && phpize && ./configure && make && make install && cd ..
  - phpenv config-add test/travis.php.ini
script:
  - ./scripts/generate-mo --quiet
  - ant phpunit lint
  - if [[ $TRAVIS_PULL_REQUEST != "false" ]] ; then ./scripts/check-dco origin/$TRAVIS_BRANCH..FETCH_HEAD ; fi
after_script:
  - if [[ -f vendor/bin/coveralls ]] ; then php vendor/bin/coveralls -v || true ; fi
